// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzhxrkyjhxhzzawwixsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6aHhya3lqaHhoenphd3dpeHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjcwMDMsImV4cCI6MjA3MTk0MzAwM30.GBPxq-0qPwkxCxWWPp6wGWCD5l1eTsevQ9yGpaCIlGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});